# Generated by Django 6.0 on 2025-12-31 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='patientrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('full_name', 'phone', 'clinic'), name='unique_active_patient_per_clinic'),
        ),
    ]
