# Generated by Django 6.0 on 2026-01-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_patientrecord_unique_active_patient_per_clinic'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecord',
            name='insurance_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Insurance Company Name'),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='insurance_phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Insurance Company Phone'),
        ),
    ]
