# Generated by Django 6.0 on 2026-01-03 20:51

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_patientrecord_insurance_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='state',
            field=models.CharField(blank=True, help_text='State, Province, or Region', max_length=100),
        ),
    ]
