# Generated by Django 6.0 on 2026-01-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_clinic_country_alter_clinic_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_type', models.CharField(choices=[('video', 'Video Box'), ('background', 'Background Image')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='ads/videos/')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='ads/backgrounds/')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('target_countries', models.TextField(blank=True, help_text='Comma-separated country codes, e.g., NG,US,GB,KE (leave blank for all countries)')),
                ('target_states', models.TextField(blank=True, help_text='Comma-separated states, e.g., Lagos,California,London (leave blank for all)')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
