# Generated by Django 6.0 on 2026-01-09 11:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_adcampaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='adcampaign',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
