# Generated by Django 6.0 on 2026-01-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_adcampaign_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adcampaign',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='adcampaign',
            name='target_countries',
            field=models.TextField(blank=True, help_text='Comma-separated country codes (auto-filled from dropdown in admin)'),
        ),
        migrations.AlterField(
            model_name='adcampaign',
            name='target_states',
            field=models.TextField(blank=True, help_text='Comma-separated states/regions (optional)'),
        ),
    ]
