# Generated by Django 6.0.9 on 2026-10-07 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_remove_adcampaign_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecord',
            name='current_medications',
            field=models.TextField(blank=True),
        ),
    ]
